"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 22:18:49.285544
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.text('lower(email)')], unique=True)

    op.create_table('workspaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_workspaces_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('slug', name=op.f('uq_workspaces_slug'))
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_owner_id'), ['owner_id'], unique=False)

    op.create_table('datasets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_datasets_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_datasets_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_datasets_workspace_id_created_at', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index('uq_datasets_workspace_name_active', ['workspace_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('workspace_memberships',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='workspacerole', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member', 'viewer')", name=op.f('ck_workspace_memberships_workspacerole')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_memberships_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_memberships_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_memberships')),
    sa.UniqueConstraint('workspace_id', 'user_id', name=op.f('uq_workspace_memberships_workspace_id_user_id'))
    )
    with op.batch_alter_table('workspace_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('dashboards',
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layout', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_dashboards_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dashboards_dataset_id_datasets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_dashboards_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboards'))
    )
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboards_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboards_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_dashboards_workspace_id_created_at', ['workspace_id', 'created_at'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('format', sa.Enum('csv', 'xlsx', 'xls', name='datasetformat', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('raw_storage_key', sa.String(length=1024), nullable=False),
    sa.Column('storage_backend', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='processingstatus', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("format IN ('csv', 'xlsx', 'xls')", name=op.f('ck_dataset_versions_datasetformat')),
    sa.CheckConstraint("status IN ('uploaded', 'processing', 'completed', 'failed')", name=op.f('ck_dataset_versions_processingstatus')),
    sa.CheckConstraint('length(checksum_sha256) = 64', name=op.f('ck_dataset_versions_checksum_len')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_dataset_versions_size_nonneg')),
    sa.CheckConstraint('version_number >= 1', name=op.f('ck_dataset_versions_version_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_dataset_versions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_versions_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_dataset_versions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_versions')),
    sa.UniqueConstraint('dataset_id', 'version_number', name=op.f('uq_dataset_versions_dataset_id_version_number'))
    )
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.create_index('ix_dataset_versions_dataset_id_checksum_sha256', ['dataset_id', 'checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_dataset_versions_workspace_id_status', ['workspace_id', 'status'], unique=False)
        batch_op.create_index('uq_dataset_versions_current', ['dataset_id'], unique=True, postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current = 1'))

    op.create_table('anomalies',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='severity', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('open', 'reviewed', 'dismissed', name='anomalystatus', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name=op.f('ck_anomalies_severity')),
    sa.CheckConstraint("status IN ('open', 'reviewed', 'dismissed')", name=op.f('ck_anomalies_anomalystatus')),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], name=op.f('fk_anomalies_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_anomalies_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomalies'))
    )
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomalies_version_id'), ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomalies_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_anomalies_workspace_id_version_id_status', ['workspace_id', 'version_id', 'status'], unique=False)

    op.create_table('dataset_artifacts',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('processed', 'cleaned', 'profile_export', name='artifactkind', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('storage_backend', sa.String(length=32), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("kind IN ('processed', 'cleaned', 'profile_export')", name=op.f('ck_dataset_artifacts_artifactkind')),
    sa.CheckConstraint('size_bytes IS NULL OR size_bytes >= 0', name=op.f('ck_dataset_artifacts_size_nonneg')),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], name=op.f('fk_dataset_artifacts_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_dataset_artifacts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_artifacts')),
    sa.UniqueConstraint('version_id', 'kind', name=op.f('uq_dataset_artifacts_version_id_kind'))
    )
    with op.batch_alter_table('dataset_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_artifacts_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('dataset_metadata',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('columns', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('profile', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('quality', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('column_count IS NULL OR column_count >= 0', name=op.f('ck_dataset_metadata_cols_nonneg')),
    sa.CheckConstraint('row_count IS NULL OR row_count >= 0', name=op.f('ck_dataset_metadata_rows_nonneg')),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], name=op.f('fk_dataset_metadata_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_dataset_metadata_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_metadata')),
    sa.UniqueConstraint('version_id', name=op.f('uq_dataset_metadata_version_id'))
    )
    with op.batch_alter_table('dataset_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_metadata_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('forecasts',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('time_column', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=16), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='resultstatus', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed')", name=op.f('ck_forecasts_resultstatus')),
    sa.CheckConstraint('horizon > 0', name=op.f('ck_forecasts_horizon_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_forecasts_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], name=op.f('fk_forecasts_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_forecasts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecasts'))
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecasts_version_id'), ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_forecasts_workspace_id_version_id', ['workspace_id', 'version_id'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('version_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', sa.Enum('profile', 'clean', 'analyze', 'forecast', 'anomaly', 'segment', 'insight', 'report', name='jobtype', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='jobstatus', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("job_type IN ('profile', 'clean', 'analyze', 'forecast', 'anomaly', 'segment', 'insight', 'report')", name=op.f('ck_processing_jobs_jobtype')),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')", name=op.f('ck_processing_jobs_jobstatus')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_processing_jobs_attempts_nonneg')),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name=op.f('ck_processing_jobs_progress_range')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_processing_jobs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], name=op.f('fk_processing_jobs_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_processing_jobs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_processing_jobs_version_id_job_type', ['version_id', 'job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_processing_jobs_workspace_id_status', ['workspace_id', 'status'], unique=False)

    op.create_table('reports',
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('draft', 'generating', 'ready', 'failed', name='reportstatus', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'generating', 'ready', 'failed')", name=op.f('ck_reports_reportstatus')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_reports_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_reports_dataset_id_datasets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], name=op.f('fk_reports_version_id_dataset_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_reports_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_version_id'), ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_reports_workspace_id_created_at', ['workspace_id', 'created_at'], unique=False)

    op.create_table('saved_analyses',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('analysis_type', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_saved_analyses_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], name=op.f('fk_saved_analyses_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_saved_analyses_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_analyses'))
    )
    with op.batch_alter_table('saved_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_analyses_version_id'), ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_analyses_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_saved_analyses_workspace_id_created_at', ['workspace_id', 'created_at'], unique=False)

    op.create_table('segments',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('profile', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('member_count >= 0', name=op.f('ck_segments_members_nonneg')),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], name=op.f('fk_segments_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_segments_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segments'))
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_version_id'), ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('insights',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('deterministic', 'ai', name='insightsource', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='severity', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name=op.f('ck_insights_severity')),
    sa.CheckConstraint("source IN ('deterministic', 'ai')", name=op.f('ck_insights_insightsource')),
    sa.ForeignKeyConstraint(['analysis_id'], ['saved_analyses.id'], name=op.f('fk_insights_analysis_id_saved_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], name=op.f('fk_insights_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_insights_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights'))
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insights_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_version_id'), ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_insights_workspace_id_version_id', ['workspace_id', 'version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('uq_users_email_lower', table_name='users')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index('ix_insights_workspace_id_version_id')
        batch_op.drop_index(batch_op.f('ix_insights_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_insights_version_id'))
        batch_op.drop_index(batch_op.f('ix_insights_analysis_id'))

    op.drop_table('insights')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_segments_version_id'))
        batch_op.drop_index(batch_op.f('ix_segments_run_id'))

    op.drop_table('segments')
    with op.batch_alter_table('saved_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_analyses_workspace_id_created_at')
        batch_op.drop_index(batch_op.f('ix_saved_analyses_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_saved_analyses_version_id'))

    op.drop_table('saved_analyses')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_workspace_id_created_at')
        batch_op.drop_index(batch_op.f('ix_reports_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_reports_version_id'))
        batch_op.drop_index(batch_op.f('ix_reports_dataset_id'))

    op.drop_table('reports')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_processing_jobs_workspace_id_status')
        batch_op.drop_index(batch_op.f('ix_processing_jobs_workspace_id'))
        batch_op.drop_index('ix_processing_jobs_version_id_job_type')

    op.drop_table('processing_jobs')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index('ix_forecasts_workspace_id_version_id')
        batch_op.drop_index(batch_op.f('ix_forecasts_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_forecasts_version_id'))

    op.drop_table('forecasts')
    with op.batch_alter_table('dataset_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_metadata_workspace_id'))

    op.drop_table('dataset_metadata')
    with op.batch_alter_table('dataset_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_artifacts_workspace_id'))

    op.drop_table('dataset_artifacts')
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_index('ix_anomalies_workspace_id_version_id_status')
        batch_op.drop_index(batch_op.f('ix_anomalies_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_anomalies_version_id'))

    op.drop_table('anomalies')
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.drop_index('uq_dataset_versions_current', postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current = 1'))
        batch_op.drop_index('ix_dataset_versions_workspace_id_status')
        batch_op.drop_index(batch_op.f('ix_dataset_versions_workspace_id'))
        batch_op.drop_index('ix_dataset_versions_dataset_id_checksum_sha256')

    op.drop_table('dataset_versions')
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index('ix_dashboards_workspace_id_created_at')
        batch_op.drop_index(batch_op.f('ix_dashboards_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_dashboards_dataset_id'))

    op.drop_table('dashboards')
    with op.batch_alter_table('workspace_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_memberships_user_id'))

    op.drop_table('workspace_memberships')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index('uq_datasets_workspace_name_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('ix_datasets_workspace_id_created_at')
        batch_op.drop_index(batch_op.f('ix_datasets_workspace_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_owner_id'))

    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
